### PR TITLE
Scale down based upon started requests

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

## Context

This is an experimental patch to help resolve a user-issue where a function may, at times, scale down to zero during an invocation. Partially because the scrape window of Prometheus is 5/10s leaving a "danger zone" and because we are currently only tracing metrics after an invocation, not as they come in.

https://github.com/openfaas-incubator/faas-idler/issues/34

## Description

Scale down based upon started requests

This patch changes from scaling down based upon completed
requests, to using started requests. This tweak should help
resolve an issue reported where a function is scaled down
whilst still executing. That happened because the metric is only
reported after the execution has completed.

## How Has This Been Tested?

In progress, help is appreciated

```
helm upgrade openfaas --install openfaas/openfaas     --namespace openfaas      --set basic_auth=true     --set functionNamespace=openfaas-fn     --set ingress.enabled=true     --set gateway.scaleFromZero=true     --set gateway.readTimeout=15m     --set gateway.writeTimeout=15m     --set gateway.upstreamTimeout=14m55s     --set queueWorker.ackWait=15m     --set faasnetes.readTimeout=5m     --set faasnetes.writeTimeout=5m     --set gateway.replicas=1     --set queueWorker.replicas=1     --set faasIdler.dryRun=false     --set faasnetes.httpProbe=true     --set faasnetes.imagePullPolicy=IfNotPresent --set clusterRole=true --set gateway.image=openfaas/gateway:0.18.7-rc4 --set faasIdler.inactivityDuration=5m --set faasIdler.reconcileInterval=30s --set faasIdler.image=openfaas/faas-idler:0.2.2-rc4 --set faasIdler.writeDebug=true
```

```
faas-cli store deploy nodeinfo --label com.openfaas.scale.zero=true -g 127.0.0.1:31112
faas-cli store deploy figlet --label com.openfaas.scale.zero=true -g 127.0.0.1:31112
```

### CODE REVIEW

**Comment by Dread1982** [comment]
I tried this version and now it seems like if a function has been invoked for at least one time, it never scales down to zero. But when the function has never been called at all, I can still reproduce the problem of scaling down during invokation (see gateway logs below)

```
2019/12/18 23:10:32 [Scale] function=mandant1-print-5 0 => 1 successful - 4.804919 seconds
2019/12/18 23:10:32 Forwarded [GET] to /healthz - [200] - 0.000737 seconds
2019/12/18 23:10:38 Forwarded [GET] to /healthz - [200] - 0.000413 seconds
2019/12/18 23:10:39 Forwarded [GET] to /system/functions - [200] - 0.002993 seconds
2019/12/18 23:10:39 Forwarded [GET] to /system/function/mandant1-print-5 - [200] - 0.004124 seconds
2019/12/18 23:10:39 Forwarded [POST] to /system/scale-function/mandant1-print-5 - [202] - 0.006075 seconds
2019/12/18 23:10:40 Forwarded [POST] to /function/mandant1-print-5 - [500] - 7.938155 seconds
```

**Comment by Dread1982** [comment]
I tried this version and it's working fine if the function has been invoked before at least one time. 

However, for a newly deployed function which has never been invoked and scaled down, if it is invoked shortly before the idler-check I now get a 500 response and it is scaled down while running.

**Comment by alexellis** [comment]
@Dread1982 can you confirm the language template that you are using?

**Comment by Dread1982** [comment]
We are using the Dockerfile template. But to reproduce the bug I also used your example mentioned in https://github.com/openfaas-incubator/faas-idler/issues/34 (https://github.com/alexellis/go-long/)

**Comment by alexellis** [comment]
@LucasRoesler and @viveksyngh both reported this PR as working as expected so I'm going to merge and release.

There may still be an issue where the stale data window (Prometheus only scrapes every N seconds) could cause a scale down during an invocation. 

Scaling down during an invocation should result in the code blocking and waiting until done, this is dependent on the template and we may look to add "preStopWait" in the Kubernetes Pod Spec to extend the safety window.

**Comment by alexellis** [comment]
Image `openfaas/faas-idler:0.3.0` is available now.

**Comment by alexellis** [comment]
@Dread1982 please see the note above, a new release of the openfaas/faas gateway is also available with the new metric.

**Comment by Dread1982** [comment]
Great, thanks! Will try it in the next days.

**Pull request merged**
