### PR TITLE
Bump docker image version to 0.1.9

### PR DESCRIPTION
**Pull request by cedricvidal**
## How Has This Been Tested?

Deployed using `kubectl apply -f faas-idler-dep.yml` and made sure the figlet sample still scaled down to 0 when not used

## Checklist:

I have:

- [x] updated the documentation if required
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
Hi,

Can you tell me more about this PR? How did you decide to bump the version?

Thanks

Alex

**Comment by cedricvidal** [comment]
Hi Alex,

Sure, the doc and deployment descriptors where not in sync with the latest released tag (0.1.9). I just updated them. Sorry, my description was not clear enough. Is it clear now? 

Cédric

**Comment by alexellis** [comment]
I've checked and that does seem to be the latest version with a valid Docker image so I'll merge, but it'd also be good to check if there's a reason for the deployment files to stay on a specific version.

I'd also check openfaas/faas and openfaas/faas-netes (YAML and Helm) to see what versions we have there too. 

Thanks for the PR 👍

**Comment by alexellis** [comment]
Congrats on having your first PR merged and for being the 152nd contributor to OpenFaaS!

**Comment by cedricvidal** [comment]
You're welcome 👍

**Pull request merged**
